# Generated by Django 5.2.11 on 2026-04-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('scientific_name', models.CharField(max_length=200)),
                ('family', models.CharField(db_index=True, max_length=150)),
                ('genus', models.CharField(db_index=True, max_length=150)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='plants/')),
            ],
        ),
    ]
