# Generated by Django 5.2.11 on 2026-05-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_altitude_plant_author_plant_collection_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='habit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='habitat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
